import "@/styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title content="Todo's"></title>
      </head>
      <body>{children}</body>
    </html>
  );
}
