import { Toaster } from "@/src/components/ui/toaster";
import connectDB from "@/src/lib/connectToMongodb";
import "@/src/styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // await connectToMongoDB();
  await connectDB();
  return (
    <html lang="en">
      <head>
        <title content="Todo's"></title>
      </head>
      <body>
        <main> {children} </main>
        <Toaster />
      </body>
    </html>
  );
}
