import LeftBar from "@/src/components/shared/LeftSidebar";
import TopBar from "@/src/components/shared/TopSidebar";
import { Toaster } from "@/src/components/ui/toaster";
import connectDB from "@/src/lib/connectToMongodb";
import "@/src/styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // await connectToMongoDB();
  await connectDB();
  return (
    <html lang="en">
      <head>
        <title content="Todo's"></title>
      </head>
      <body>
        <div className="w-full md:flex  h-screen md:overflow-hidden overflow-y-scroll overflow-x-hidden">
          <TopBar />
          <LeftBar />
          <section className="flex flex-1 h-full overflow-x-hidden">{children}</section>
          {/* <BottomBar /> */}
        </div>

        <Toaster />
      </body>
    </html>
  );
}
