import BottomBar from "@/src/components/shared/BottomBar";
import LeftBar from "@/src/components/shared/LeftSidebar";
import TopBar from "@/src/components/shared/TopSidebar";
import { Toaster } from "@/src/components/ui/toaster";
import connectDB from "@/src/lib/connectToMongodb";
import getActiveUserData from "@/src/server/user/getActiveUserData";
import "@/src/styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // await connectToMongoDB();
  await connectDB();
  const { user } = await getActiveUserData();
  // console.log({ user });
  return (
    <html lang="en">
      <head>
        <title content="Todo's"></title>
      </head>
      <body>
        <div className="w-full md:flex  h-screen md:overflow-hidden overflow-y-scroll overflow-x-hidden">
          {!user ? (
            <section className="flex flex-1 h-full overflow-x-hidden">{children}</section>
          ) : (
            <>
              <TopBar />
              <LeftBar />
              <BottomBar />
              <section className="flex flex-1 h-full overflow-x-hidden">{children}</section>
            </>
          )}
        </div>

        <Toaster />
      </body>
    </html>
  );
}
